# Generated by Django 3.2.9 on 2021-12-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('image_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('seekingVenue', models.BooleanField()),
                ('seekingDescription', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Artist',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('image_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('seekingTalent', models.BooleanField()),
                ('seekingDescription', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Venue',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyyur.artist')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyyur.venue')),
            ],
            options={
                'verbose_name_plural': 'Show',
            },
        ),
    ]
