# Generated by Django 3.2.9 on 2021-12-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='venue_id',
            new_name='venue',
        ),
    ]
