# Generated by Django 3.2.9 on 2021-12-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0003_auto_20211206_2237'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='show',
            table='show',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
    ]
