# Generated by Django 3.2.9 on 2021-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0004_auto_20211206_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook_link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seekingDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.CharField(max_length=1000),
        ),
    ]
