# Generated by Django 3.2.9 on 2021-12-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0007_auto_20211212_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook_link',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_link',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='seekingDescription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='state',
            field=models.TextField(max_length=1000),
        ),
    ]
