# Generated by Django 3.2.9 on 2021-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0009_auto_20211212_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
