# Generated by Django 3.2.9 on 2021-12-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0011_auto_20211226_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
