# Generated by Django 3.2.9 on 2021-12-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0013_auto_20211226_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='fyyur.artist'),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='fyyur.venue'),
        ),
    ]
