# Generated by Django 3.2.9 on 2021-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0014_auto_20211226_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
