# Generated by Django 3.2.9 on 2021-12-28 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0015_alter_show_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='genres',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook_link',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook_link',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
