# Generated by Django 3.2.9 on 2021-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0016_auto_20211228_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='genres',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
