# Generated by Django 3.2.9 on 2021-12-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0017_alter_venue_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='seekingDescription',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seekingDescription',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
