# Generated by Django 3.2.9 on 2021-12-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0018_auto_20211228_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='seekingVenue',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seekingTalent',
            field=models.BooleanField(default=False),
        ),
    ]
